export const SubjectDocumentationPageMapping = [
    { uiLabel: 'Study Number', dbColumn: 'StudyNumber', highlight: true },
    { uiLabel: 'Clinical Phase', dbColumn: 'StudyPhase', highlight: true },
    { uiLabel: 'Indication', dbColumn: 'StudyIndication', highlight: true },
    { uiLabel: 'Scientific Area', dbColumn: 'studyscientificarea', highlight: true },
    { uiLabel: 'Data Classification', dbColumn: '', highlight: true },
    { uiLabel: 'Label', dbColumn: '', highlight: false },
    { uiLabel: 'Hierarchy', dbColumn: '', highlight: false },
    { uiLabel: 'Subject Type', dbColumn: '', highlight: false },
    { uiLabel: 'First Name', dbColumn: '', highlight: false },
    { uiLabel: 'Last Name', dbColumn: 'IdpCreatedBy', highlight: false },
    { uiLabel: 'Date of Birth', dbColumn: 'studysource', highlight: false },
    { uiLabel: 'State', dbColumn: 'StudyType', highlight: false },  
    { uiLabel: 'Sex', dbColumn: '', highlight: false },
    { uiLabel: 'ML Set', dbColumn: '', highlight: false },
    { uiLabel: 'Race', dbColumn: '', highlight: false },
    { uiLabel: 'Ethnicity', dbColumn: '', highlight: false },
    { uiLabel: 'Species', dbColumn: '', highlight: false },
    { uiLabel: 'Strain', dbColumn: '', highlight: false },
]